apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}

spec:
  selector:
   matchLabels:
    app: {{.Values.deployment.name}}

  replicas: 1
  
  template:
    metadata:
      labels:
        app: {{.Values.deployment.name}}

    spec:
      containers:
      - name: {{.Values.deployment.name}}
        image: richardchesterwood/k8s-fleetman-helm-demo:v1.0.0-dev
