apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}

spec:
  selector:
   matchLabels:
    app: {{.Values.deployment.name}}

  replicas: 1
  
  template:
    metadata:
      labels:
        app: {{.Values.deployment.name}}

    spec:
      containers: {{- include "webAppImage" . | indent 6}}
