apiVersion: v1
kind: Service
metadata:
  name: {{.Values.environment.isDev | ternary .Values.environment.developmentNameEnvironment .Values.environment.productionNameEnvironment}}-{{.Values.service.name}}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{.Values.environment.isDev | ternary .Values.environment.developmentNameEnvironment .Values.environment.productionNameEnvironment}}-{{.Values.deployment.name}}

  ports:
    - name: http
      port: 80
      nodePort: {{add .Values.service.nodePort (.Values.environment.isDev | ternary 0 100) }}

  type: NodePort