deployment:
  name: app
  imageRepo: richardchesterwood

service:
  name: service
  nodePort: 30003

environment:
  isDev: true
  productionNameEnvironment: production
  developmentNameEnvironment: development